### ISSUE TITLE
req.query instead of req.body in /api/todo PUT and DELETE

### ISSUE THREAD

**Issue by rlane85** [Blane245/lane-db#28]
sending a request of type PUT or DELETE with body `{description: text}` receiving status 400 and reply

`{"msg": "Description must be provided and not blank!"}`
or 
`{list: []}`

**To Reproduce**
1. send PUT or DELETE request to /api/todo with `{description: "anything"}` body
2. see reply!

**Expected behavior**
modify ToDos with matching description

**Screenshots**
![Screenshot (18)](https://github.com/Blane245/lane-db/assets/44262357/05b2eccb-092e-42fc-807c-9478787371f5)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: Postman
 - Version 0.4

**Edit to add:**
I forgot to mention: I believe it should be a simple fix to actually remove this bug. 

todo.controller.js starting at line 139. 
Probably should be using `req.body` instead of `req.query`. a la the title of the issue 👌😂🤣

**Additional context**

I'd suggesting changing the behavior of these endpoints while you are looking at this issue. Initially, I was assuming I would send a PUT request to modify a TODO and the key that the lanedb server would look for to match the Todo in the database would be the "ID" field. But it is matching the description it looks like. Also, the way this endpoint currently is set up, there is no way to modify the description. Since it is the field being used to match which entry (or entries?) the request is trying to modify

**Comment by Blane245** [comment]
It's a put not a post

**Comment by rlane85** [comment]
the POST version works just fine
PUT and DELETE not

**Comment by rlane85** [comment]
![Screenshot (18)](https://github.com/Blane245/lane-db/assets/44262357/3c72754b-24d3-4d01-8cc4-a17888ffdc19)

**Comment by Blane245** [comment]
client switched put and get to parameters
